In [2]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


# Layers Without Parameters

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [5]:
layer = CenteredLayer()
layer(torch.tensor([1.0,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

# Layers With Parameters

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.3051,  0.8208, -0.3505],
        [ 0.2353,  1.1918,  1.1107],
        [-1.0852, -0.0133,  1.1061],
        [ 1.9006,  1.3486,  0.6294],
        [-1.0402, -0.7423, -0.9481]], requires_grad=True)

In [10]:
linear(torch.rand(2,5))

tensor([[0.3303, 0.0000, 0.0000],
        [2.7136, 2.4854, 0.3358]])

In [14]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.2417],
        [1.6043]])