# Testing

In [1]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [2]:
cpu_device = torch.device("cpu")

In [3]:
x = torch.ones(1, device = cpu_device)

# D2l Begins Here

In [4]:
import torch
from torch import nn
from d2l import torch as d2l

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


# Computing Devices

In [6]:
def cpu():
    return torch.device('cpu')

def gpu(i = 0):
    return torch.device(f'mps:{i}')

cpu(), gpu(), gpu(1)

(device(type='cpu'), device(type='mps', index=0), device(type='mps', index=1))

In [8]:
def num_gpus():
    return torch.mps.device_count()

num_gpus()

1

In [9]:
# Let's us run code even if requested GPU/s don't/doesn't exist

def try_gpu(i = 0):
    if num_gpus() >= i + 1:
        return gpu(i)
    else:
        return cpu()

def try_all_gpus():
    return [gpu(i) for i in range(num_gpus())]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='mps', index=0),
 device(type='cpu'),
 [device(type='mps', index=0)])

# Tensors and GPUs

In [18]:
x = torch.arange(4)
x.device

device(type='cpu')

# Storage on the GPUs

In [20]:
X = torch.ones(2,3, device = try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='mps:0')

# Neural Network and GPUs

In [21]:
net = nn.Sequential(nn.LazyLinear(1))
net = net.to(device = try_gpu())

In [22]:
net(X)

tensor([[-0.2836],
        [-0.2836]], device='mps:0', grad_fn=<LinearBackward0>)

In [25]:
net[0].weight.data.device

device(type='mps', index=0)