In [1]:
import torch
from torch import nn

In [7]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size = (2, 4))
net(X).shape

torch.Size([2, 1])

# Parameter Access

In [10]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[-2.6908e-01,  2.9636e-01, -3.4931e-01, -2.1957e-01, -1.3318e-01,
                       -1.5095e-02,  2.6907e-04,  9.6463e-02]])),
             ('bias', tensor([-0.3327]))])

# Targeted Parameters

In [ ]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([-0.3327]))

In [12]:
net[2].weight.grad == None

True

# All Parameters at Once

In [17]:
[(name, param.shape) for name, param in net.named_parameters()]


[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

# Tied Parameters

In [ ]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), shared, nn.ReLU(), shared, nn.ReLU(), nn.LazyLinear(1))

net(X)


print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0,0] = 100
print(net[2].weight.data[0] == net[4].weight.data[0])
# Layers 2 and 4 share all of the same features -- they are tied to each other. Change one and you automatically change the other
# They are the same object

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
