In [1]:
import torch
from torch import nn

In [3]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size = (2, 4))
net(X).shape

torch.Size([2, 1])

# Built-in Initialization

In [4]:
def init_normal(module):
    if type(module) == nn.Linear:
        nn.init.normal_(module.weight, mean = 0, std = 0.01)
        nn.init.zeros_(module.bias)

net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([ 0.0026, -0.0168, -0.0117,  0.0090]), tensor(0.))

In [5]:
def init_constant(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 1)
        nn.init.zeros_(module.bias)

net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [11]:
def init_xavier(module):
    if type(module) == nn.Linear:
        nn.init.xavier_uniform_(module.weight)

net[0].apply(init_constant)
net[2].apply(init_xavier)

print(net[0].weight.data[0])
print(net[2].weight.data[0])

tensor([1., 1., 1., 1.])
tensor([ 0.0097,  0.7569,  0.3144,  0.0197, -0.4375, -0.1026,  0.7225, -0.1161])


# Custom Initialization

In [ ]:
def my_init(module):
    if type(module) == nn.Linear:
        # More custom stuff here -- Nothing different from up above except there's no specific package like xavier_uniform_ (or there's extra stuff)

In [16]:
# We can also set parameters directly

print(net[0].weight.data[:1])
net[0].weight.data[:] += 1
net[0].weight.data[0,0] = 42
net[0].weight.data[0]


tensor([[42.,  5.,  5.,  5.]])


tensor([42.,  6.,  6.,  6.])